<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Treść',
    'Entity' => 'Entity',
    'Entity ID' => 'Entity ID',
    'Parent ID' => 'Parent ID',
    'Status' => 'Status',
    'Level' => 'Poziom',
    'Created by' => 'Utworzony przez',
    'Updated by' => 'Related to',
    'Related to' => 'Related to',
    'Url' => 'Url',
    'Created date' => 'Data utworzenia',
    'Updated date' => 'Data edycji',
    'View' => 'Podejrzyj',
    'Update' => 'Edytuj',
    'Delete' => 'Usuń',
    'Reply' => 'Odpowiedz',
    'Comments ({0})' => 'Komentarze ({0})',
    'Comment cannot be blank.' => 'Komentarz nie może być pusty.',
    'Comment has not been deleted. Please try again!' => 'Komentarz nie został usunięty. Spróbuj ponownie później!',
    'Add a comment...' => 'Dodaj komentarz...',
    'Comment' => 'Skomentuj',
    'Oops, something went wrong. Please try again later.' => 'Ups, coś poszło nie tak. Spróbuj ponownie później.',
    'The requested page does not exist.' => 'Żądana strona nie istniej.',
    'Comment has been deleted.' => 'Komentarz został usunięty..',
    'Comment has been saved.' => 'Komentarz został zapisany.',
    'Click here to cancel reply.' => 'Kliknij tutaj, aby anulować odpowiedź.',
    'Comments Management' => 'Zarządzanie komentarzami',
    'Select Status' => 'Wybierz status',
    'Select Author' => 'Wybierz autora',
    'Update Comment: {0}' => 'Update Comment: {0}',
    'Active' => 'Aktywny',
    'Deleted' => 'Usunięty',
    'Go Back' => 'Wróć',
];
